-- The tables are created by Terraform (infra/main/bigquery.tf) from sql/demand_schema.json.
-- This file only documents the design.
--
-- raw_demand_versions: append-only. One row per (report, interval_start, zone, version), forever.
-- current_demand:      latest known value per (report, interval_start, zone), kept by MERGE.
--
-- Both tables have the same columns:
--   report, measure          which report, and what the number means (ontario_demand | total_load)
--   interval_start           UTC, normalised from IESO's EST hour-ending convention
--   zone                     'ONTARIO'
--   version                  the _vN of the file the value came from
--   value_mw
--   published_at             IESO's Last-Modified (when the value became known)
--   ingested_at              when the producer saw it
--   loaded_at                when the consumer wrote it to BigQuery
--   source_uri, content_sha256, reason (live | backfill | reconciliation)
--
-- PARTITION BY DATE(interval_start), CLUSTER BY report, zone.
